Шаблон страницы компонента
js-tasks-ru/htmlcss-20230911-4_frenky233 pull request #12
Opened 2023-10-02 11:11 UTC by Frenky233

2023-10-02 11:29 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-02 19:46 UTC, GSemikozov requested changes

2023-10-02 19:46 UTC, GSemikozov commented on components/container/container.css
> +	height: 100%;
вот это точно лишнее

2023-10-02 19:46 UTC, GSemikozov commented on components/font-colors/fourth.css
> +.fourth{
все эти штуки лучше сложить в один общий файл и уже его подключать в main

2023-10-02 19:46 UTC, GSemikozov commented on components/component-page/__footer/component-page__footer.css
> +	padding-top: 92px;
паддинги - это все-таки внутреннее дело компонента, я бы рекомендовал работать через модификатор блока

2023-10-04 10:30 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-04 10:30 UTC, Frenky233 commented on components/container/container.css
> +	height: 100%;
убрал

2023-10-04 10:30 UTC, Frenky233 commented on components/font-colors/fourth.css
> +.fourth{
сложил в typography.css

2023-10-04 10:31 UTC, Frenky233 commented on components/component-page/__footer/component-page__footer.css
> +	padding-top: 92px;
поменял

2023-10-05 20:10 UTC, GSemikozov approved these changes

2023-10-05 20:10 UTC, merged