Avatar task
js-tasks-ru/htmlcss-20230911-4_frenky233 pull request #14
Opened 2023-10-06 11:31 UTC by Frenky233

2023-10-06 11:32 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-07 21:26 UTC, GSemikozov requested changes

2023-10-07 21:26 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.avatar__wrapper{
в нашем случае это лишнее - аватар будет 3 размеров, он не должен быть резиновым.

2023-10-10 19:29 UTC, GSemikozov requested changes

2023-10-10 19:29 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.avatar__wrapper{
этот элемент в целом лишний, его надо удалить. А на уровне блока задать размеры 102х102

2023-10-12 16:57 UTC, Frenky233 commented on 06-lection4/01-avatar/avatar.css
> +.avatar__wrapper{
сделал

2023-10-13 21:47 UTC, GSemikozov approved these changes

2023-10-13 21:48 UTC, merged