Background-image task
js-tasks-ru/htmlcss-20230911-4_frenky233 pull request #15
Opened 2023-10-06 11:45 UTC by Frenky233

2023-10-06 12:05 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-07 21:27 UTC, GSemikozov requested changes

2023-10-07 21:27 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +@media all and (min-width:400px) and (max-width:768px){
здесь и ниже - max-width лишние

2023-10-08 14:37 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-08 14:37 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-10-10 19:29 UTC, GSemikozov approved these changes

2023-10-10 19:30 UTC, merged