Checkbox task
js-tasks-ru/htmlcss-20230911-4_frenky233 pull request #17
Opened 2023-10-08 21:23 UTC by Frenky233

2023-10-10 19:36 UTC, GSemikozov requested changes

2023-10-10 19:36 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +	display: inline-flex;
и position: relative

2023-10-10 19:36 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox__input:focus ~ .checkbox__state .checkbox__title{
общие стили для .checkbox__title не описаны

2023-10-10 19:36 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +	color: var(--text-third) !important;
а зачем !important?)

2023-10-12 16:59 UTC, Frenky233 commented on 07-lection5/01-checkbox/checkbox.css
> +	color: var(--text-third) !important;
убрал, в typogaphy.css лежат классы с цветам !important

2023-10-12 16:59 UTC, Frenky233 commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox__input:focus ~ .checkbox__state .checkbox__title{
добавил

2023-10-12 16:59 UTC, Frenky233 commented on 07-lection5/01-checkbox/checkbox.css
> +	display: inline-flex;
добавил

2023-10-13 21:48 UTC, GSemikozov approved these changes

2023-10-13 21:49 UTC, merged