Toggler task
js-tasks-ru/htmlcss-20230911-4_frenky233 pull request #19
Opened 2023-10-08 21:24 UTC by Frenky233

2023-10-10 19:38 UTC, GSemikozov requested changes

2023-10-10 19:38 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +.toggler{
см комменты по чекбоксу

2023-10-12 16:59 UTC, Frenky233 commented on 07-lection5/03-toggler/toggler.css
> +.toggler{
аналогично)

2023-10-13 21:49 UTC, GSemikozov approved these changes

2023-10-13 21:49 UTC, merged