burger-menu+theme-changer
js-tasks-ru/htmlcss-20230911-4_frenky233 pull request #22
Opened 2023-10-15 15:12 UTC by Frenky233

2023-10-15 15:13 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-18 14:24 UTC, GSemikozov requested changes

2023-10-18 14:24 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    fill: var(--primary);
нам бы поправить немного свг и использовать color здесь - будет более надежно)

2023-10-18 14:24 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +.toggler__hidden{
модификатор состояния? или все-таки элемент?

2023-10-18 14:24 UTC, GSemikozov commented on components/header/__mobile-menu-button/_close/header__mobile-menu-button_close.css
> +.header__mobile-menu-button_close{
просто .header__close

2023-10-18 14:24 UTC, GSemikozov commented on index.html
> +                    <h2 class="footer__title primary">About</h2>
просто primary? неясно что именно у нас ту primary. Наверно `font font_primary` ?

2023-10-18 22:44 UTC, Frenky233 commented on 05-lection3/01-tooltip/tooltip.css
> +    fill: var(--primary);
поменял

2023-10-18 22:45 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-18 22:45 UTC, Frenky233 commented on 07-lection5/03-toggler/toggler.css
> +.toggler__hidden{
модификатор, исправил

2023-10-18 22:45 UTC, Frenky233 commented on components/header/__mobile-menu-button/_close/header__mobile-menu-button_close.css
> +.header__mobile-menu-button_close{
поменял

2023-10-18 22:45 UTC, Frenky233 commented on index.html
> +                    <h2 class="footer__title primary">About</h2>
поменял на font-color-primary

2023-10-22 19:42 UTC, GSemikozov requested changes

2023-10-22 19:42 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +	fill: var(--grey-3);
везде лучше обращаться через color и на уровне кода иконок проставить currentColor

2023-10-22 19:42 UTC, GSemikozov commented on components/mobile-menu/mobile-menu.css
> +.mobile-menu[data-open] ~ .main{
вот это оч неправильно - подвязывать к изменению состояния данного блока поведение других блоков, которые о состоянии .mobile-menu ничего не должны знать)
можно просто через js overflow: hidden на body ставить, и все

2023-10-22 19:42 UTC, GSemikozov commented on components/mobile-menu/mobile-menu.css
> +.mobile-menu[data-open] ~ .footer{
и это тоже лишнее

2023-10-23 14:30 UTC, Frenky233 commented on components/mobile-menu/mobile-menu.css
> +.mobile-menu[data-open] ~ .main{
так и сделал, спасибо за совет

2023-10-23 14:30 UTC, Frenky233 commented on 07-lection5/03-toggler/toggler.css
> +	fill: var(--grey-3);
поменял

2023-10-23 14:30 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-23 14:30 UTC, Frenky233 commented on components/mobile-menu/mobile-menu.css
> +.mobile-menu[data-open] ~ .footer{
убрал

2023-10-25 18:39 UTC, GSemikozov approved these changes

2023-10-25 18:40 UTC, merged