3rd task
js-tasks-ru/htmlcss-20230911-4_frenky233 pull request #3
Opened 2023-09-18 11:06 UTC by Frenky233

noramlize.css + разметка

2023-09-18 11:15 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-09-18 21:50 UTC, GSemikozov requested changes

2023-09-18 21:50 UTC, GSemikozov commented on components/footer/__body/footer__body.css
> +.footer__body{
такая структура блока выбрана сознательно? 
я к тому, что мы договаривались не следовать этим рекомендациям БЭМ и сохранять плоскую структуру классов. Но - если нравится такой подход, то тогда придется следовать ему и дальше по курсу

2023-09-18 21:50 UTC, GSemikozov commented on components/footer/footer.css
> +	height: 300px;
лишнее ограничение высоты

2023-09-18 21:50 UTC, GSemikozov commented on components/footer/footer.css
> +	box-sizing: border-box;
можно унести в normalize

2023-09-18 21:50 UTC, GSemikozov commented on components/footer/footer.css
> +	padding-block: 5rem;
а это для чего?)

2023-09-18 21:50 UTC, GSemikozov commented on components/footer/footer.css
> +	font-size: 20px;
на весь блок по умолчанию 20px не нужно, лучше каждому конкретному текстовому элементу задать свое значение

2023-09-18 21:50 UTC, GSemikozov commented on components/header/__title/header__title.css
> +	display: table-cell;
а зачем table-cell?)

2023-09-18 21:50 UTC, GSemikozov commented on components/header/header.css
> +	display: table;
не стоит превращать в таблицу (если бы это была таблица - тогда ок)

2023-09-18 21:50 UTC, GSemikozov commented on components/header/header.css
> +	height: 237px;
лишнее ограничение

2023-09-18 21:50 UTC, GSemikozov commented on components/main/main.css
> +	margin-inline: -15rem;
а зачем эти margin-inline + padding-inline? удалим

2023-09-18 21:50 UTC, GSemikozov commented on components/page/page.css
> +	padding-left: 15rem;
здесь паддинги не нужны (дальше мы узнаем как обработать эту ситуацию)

2023-09-19 03:49 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-09-19 20:46 UTC, Frenky233 commented on components/footer/footer.css
> +	height: 300px;
убрал

2023-09-19 20:46 UTC, Frenky233 commented on components/footer/footer.css
> +	box-sizing: border-box;
унёс

2023-09-19 20:47 UTC, Frenky233 commented on components/footer/footer.css
> +	padding-block: 5rem;
было для падддингов сверху и снизу, сейчас поставил просто padding

2023-09-19 20:47 UTC, Frenky233 commented on components/footer/footer.css
> +	font-size: 20px;
поменял

2023-09-19 20:49 UTC, Frenky233 commented on components/header/__title/header__title.css
> +	display: table-cell;
было что-бы vertical-allign: middle работал в ограниченной высоте, сейчас убрал ограничение по высоте и поставил padding

2023-09-19 20:49 UTC, Frenky233 commented on components/header/header.css
> +	display: table;
так же как и в header__title

2023-09-19 20:49 UTC, Frenky233 commented on components/header/header.css
> +	height: 237px;
убрал

2023-09-19 20:51 UTC, Frenky233 commented on components/main/main.css
> +	margin-inline: -15rem;
было что-бы border был по всей ширине страницы, а контент внутри с отступами

2023-09-19 20:51 UTC, Frenky233 commented on components/page/page.css
> +	padding-left: 15rem;
понял

2023-09-20 19:44 UTC, GSemikozov requested changes

2023-09-20 19:44 UTC, GSemikozov commented on components/footer/footer-inner/__desc/footer-inner__desc.css
> +.footer-inner__desc{
блок в блоке? .footer-inner в футере? это ошибка. Если хочется как отдельный блок - тогда надо оформить как отдельный блок)

2023-09-21 19:09 UTC, Frenky233 commented on components/footer/__body/footer__body.css
> +.footer__body{
Скорее нет, просто надо было какую-то структуру в футере что-бы двигать текст и заголовок вместе, сейчас убрал это

2023-09-21 19:09 UTC, Frenky233 commented on components/footer/footer-inner/__desc/footer-inner__desc.css
> +.footer-inner__desc{
убрал

2023-09-21 20:49 UTC, GSemikozov approved these changes

2023-09-21 20:50 UTC, merged