1st commit button
js-tasks-ru/htmlcss-20230911-4_frenky233 pull request #4
Opened 2023-09-19 05:33 UTC by Frenky233

кнопка

2023-09-19 19:39 UTC, GSemikozov requested changes

2023-09-19 19:39 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +	width: 189px;
лишнее ограничение

2023-09-19 19:39 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +	font-size: 16px;
не хватает font-family + padding

2023-09-19 19:39 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +	border: 1.5px solid var(--grey-3);
1

2023-09-19 19:39 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +	border: 1.5px solid var(--black);
на ховер меняет только border-color

2023-09-19 19:52 UTC, Frenky233 commented on 03-lection1/01-button/button.css
> +	border: 1.5px solid var(--black);
Так и в макете только цвет границы меняется

2023-09-19 19:53 UTC, Frenky233 commented on 03-lection1/01-button/button.css
> +	font-size: 16px;
font-family в main.css лежит, он сразу там лежал

2023-09-19 19:55 UTC, Frenky233 commented on 03-lection1/01-button/button.css
> +	width: 189px;
убрал

2023-09-19 19:55 UTC, Frenky233 commented on 03-lection1/01-button/button.css
> +	font-size: 16px;
padding добавил

2023-09-19 19:55 UTC, Frenky233 commented on 03-lection1/01-button/button.css
> +	border: 1.5px solid var(--grey-3);
поменял

2023-09-19 20:00 UTC, Frenky233 commented on 03-lection1/01-button/button.css
> +	border: 1.5px solid var(--black);
исправил

2023-09-20 19:45 UTC, GSemikozov requested changes

2023-09-20 19:45 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +	padding: 15px 65px;
нужно либо добавить высоту, либо тогда паддинги прописать более корретно чтобы высота была как в макете) `15px 65px 14px`

2023-09-21 19:11 UTC, Frenky233 commented on 03-lection1/01-button/button.css
> +	padding: 15px 65px;
прописал

2023-09-21 20:51 UTC, GSemikozov requested changes

2023-09-21 20:51 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +	font-size: 16px;
не хватает стилей для описания текста - font-family, font-weight, line-height

2023-09-22 15:22 UTC, Frenky233 commented on 03-lection1/01-button/button.css
> +	font-size: 16px;
добавил

2023-09-24 21:32 UTC, GSemikozov approved these changes

2023-09-24 21:33 UTC, merged