1st commit accordion
js-tasks-ru/htmlcss-20230911-4_frenky233 pull request #5
Opened 2023-09-19 05:34 UTC by Frenky233

аккордион

2023-09-19 05:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-09-19 05:34 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-09-19 19:38 UTC, GSemikozov requested changes

2023-09-19 19:38 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +	width: 730px;
лишнее огранчение

2023-09-19 19:38 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +	height: 72px;
и это

2023-09-19 19:38 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +	border: 2px solid var(--grey-3);
а почему 2px?)

2023-09-19 19:38 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion{
как и говорил на занятии, описывая ДЗ - это секция / элемент аккордиона, а не сам аккордион (accordion__section)

2023-09-19 19:38 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +	height: 144px;
лишнее

2023-09-19 19:38 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +	padding: 24px 32px 0;
общие паддинги лучше задавать на уровне родителя

2023-09-19 19:38 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +	margin: 16px 32px 32px;
чтобы в том числе не задавать вот такие марджины у другого дочернего элемента

2023-09-19 19:38 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +            <p class="accordion__content">
div

2023-09-19 19:55 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-09-19 20:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-09-19 20:46 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-09-19 20:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-09-19 20:53 UTC, Frenky233 commented on 03-lection1/02-accordion/accordion.css
> +	width: 730px;
убрал на блоке accordion__section, но поставил на блок accordion, иначе он по всей ширине растягивается

2023-09-19 20:53 UTC, Frenky233 commented on 03-lection1/02-accordion/accordion.css
> +	height: 72px;
убрал

2023-09-19 20:54 UTC, Frenky233 commented on 03-lection1/02-accordion/accordion.css
> +	border: 2px solid var(--grey-3);
поставил 1, 2px по моему выгладило лучше что ли)

2023-09-19 20:55 UTC, Frenky233 commented on 03-lection1/02-accordion/accordion.css
> +.accordion{
понял здесь, поменял

2023-09-19 20:55 UTC, Frenky233 commented on 03-lection1/02-accordion/accordion.css
> +	height: 144px;
убрал

2023-09-19 20:55 UTC, Frenky233 commented on 03-lection1/02-accordion/accordion.css
> +	margin: 16px 32px 32px;
убрал

2023-09-19 20:55 UTC, Frenky233 commented on 03-lection1/02-accordion/accordion.css
> +	padding: 24px 32px 0;
поставил на родитель

2023-09-19 20:55 UTC, Frenky233 commented on 03-lection1/02-accordion/index.html
> +            <p class="accordion__content">
поменял, но с задачника p был, ладно

2023-09-19 21:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-09-19 21:53 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-09-20 19:45 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +	width: 730px;
не надо, пусть растягивается)

2023-09-20 19:46 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +	border: 2px solid var(--grey-3);
в макете 1)

2023-09-20 19:47 UTC, GSemikozov requested changes

2023-09-20 19:47 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion{
все равно уберем

2023-09-20 19:47 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion-section{
.accordion__section

2023-09-21 19:08 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-09-21 19:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-09-21 19:14 UTC, Frenky233 commented on 03-lection1/02-accordion/accordion.css
> +.accordion-section{
То есть, если мы описываем accordion__section как элемент, тогда заголовок и контент это элементы элемента или их как-то в отдельный блок надо?

2023-09-21 20:52 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion-section{
нет, мы не должны привязываться к уровню вложенностей элементов, наоборот - соблюдаем плоскую структуру классов: .accordion__section, .accordion__title, .accordion__content и тд

2023-09-22 15:20 UTC, Frenky233 commented on 03-lection1/02-accordion/accordion.css
> +.accordion-section{
понял, поменял

2023-09-22 15:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-09-22 15:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-09-22 18:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-09-24 21:33 UTC, GSemikozov approved these changes

2023-09-24 21:34 UTC, merged